Added check to see if job already exists

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -90,12 +90,23 @@ jobs:
 
       - name: Deploy Cloud Run Job
         run: |
-          gcloud beta run jobs create ${{ secrets.JOB_NAME }} \
-          --image asia-south1-docker.pkg.dev/architect-learning-435310/recommendations-engine/recommendations-pre-processor-job \
-          --project ${{ secrets.PROJECT_ID }} \
-          --region ${{ secrets.PROJECT_REGION }} \
-          --set-env-vars "DB_URL=${{ secrets.POSTGRES_DB_URL }},DB_USERNAME=${{ secrets.POSTGRES_DB_USERNAME }},DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }},OUTPUT_PATH=${{ secrets.OUTPUT_PATH }}" \
-          --args="${{ secrets.GCP_STORAGE_BUCKET_INPUT_PATH }}","${{ secrets.GCP_STORAGE_BUCKET_NAME }}"
+          JOB_EXISTS=$(gcloud beta run jobs describe ${{ secrets.JOB_NAME }} --project ${{ secrets.PROJECT_ID }} --region ${{ secrets.PROJECT_REGION }} --format="value(name)" || echo "not found")    
+          if [ "$JOB_EXISTS" != "not found" ]; then
+            echo "Job already exists, updating..."
+            gcloud beta run jobs update ${{ secrets.JOB_NAME }} \
+            --image asia-south1-docker.pkg.dev/architect-learning-435310/recommendations-engine/recommendations-pre-processor-job \
+            --project ${{ secrets.PROJECT_ID }} \
+            --region ${{ secrets.PROJECT_REGION }} \
+            --set-env-vars "DB_URL=${{ secrets.POSTGRES_DB_URL }},DB_USERNAME=${{ secrets.POSTGRES_DB_USERNAME }},DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }},OUTPUT_PATH=${{ secrets.OUTPUT_PATH }}" \
+            --args="${{ secrets.GCP_STORAGE_BUCKET_INPUT_PATH }}","${{ secrets.GCP_STORAGE_BUCKET_NAME }}"
+          else
+            echo "Job does not exist, creating a new job..."
+            gcloud beta run jobs create ${{ secrets.JOB_NAME }} \
+            --image asia-south1-docker.pkg.dev/architect-learning-435310/recommendations-engine/recommendations-pre-processor-job \
+            --project ${{ secrets.PROJECT_ID }} \
+            --region ${{ secrets.PROJECT_REGION }} \
+            --set-env-vars "DB_URL=${{ secrets.POSTGRES_DB_URL }},DB_USERNAME=${{ secrets.POSTGRES_DB_USERNAME }},DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }},OUTPUT_PATH=${{ secrets.OUTPUT_PATH }}" \
+            --args="${{ secrets.GCP_STORAGE_BUCKET_INPUT_PATH }}","${{ secrets.GCP_STORAGE_BUCKET_NAME }}"
 
       - name: Slack notification
         uses: 8398a7/action-slack@v3
